apiVersion: v1
kind: Secret
metadata:
  name: rednorte-secrets
  namespace: rednorte
type: Opaque
stringData:
  POSTGRES_USER: root
  POSTGRES_PASSWORD: root123
  JWT_SECRET: clave_secreta_desarrollo
  RABBITMQ_DEFAULT_USER: root
  RABBITMQ_DEFAULT_PASS: root123
